import Head from 'next/head';
import Navbar from '../components/navbar';
import Header from '../components/header';
import About from '../components/about';
import Portfolio from '../components/portfolio';
import Contact from '../components/contact';
export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<div className="mainWrap">
				<Navbar />
				<Header />
				<About />
				<Portfolio />
				<Contact />
			</div>
		</div>
	);
}
